name: mixpanel_flutter_example
description: Demonstrates how to use the mixpanel_flutter plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mixpanel_flutter:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  mixpanel_example: any
flutter:
  uses-material-design: true

